multibuild

diff --git a/Dockerfile.ubuntu-24.04 b/Dockerfile.ubuntu-24.04
--- a/Dockerfile.ubuntu-24.04
+++ b/Dockerfile.ubuntu-24.04
@@ -45,11 +45,15 @@ RUN set -eux ; \
   libxkbcommon-dev \
   libxkbcommon-x11-dev
 
-# --parallel removed to not get killed
+# separate to speedup retries
 RUN set -eux ; \
   mkdir /ghjk ; cd /ghjk ; \
   wget https://download.qt.io/official_releases/qt/6.6/6.6.3/single/qt-everywhere-src-6.6.3.tar.xz ; \
-  tar -xvof qt-everywhere-src-6.6.3.tar.xz ; \
+  tar -xvof qt-everywhere-src-6.6.3.tar.xz
+
+# --parallel removed to not get killed
+RUN set -eux ; \
+  cd /ghjk ; \
   mkdir build ; cd build ; \
   ../qt-everywhere-src-6.6.3/configure -static ; \
   cmake --build . ; \
